# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextMaker

  # RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'

  # SnapKit
  pod 'SnapKit'

  # Then
  pod 'Then'

end
