# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextMaker

  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxGesture'
  pod 'RxDataSources', '~> 5.0'

  # SnapKit
  pod 'SnapKit', '~> 5.6.0'

  # Then
  pod 'Then'

end
